In [1]:
import analyzer.plotting
import peakquality as pq
import pickle
import analyzer
from analyzer.datasets import SampleManager
from analyzer.core import AnalysisResult
import numpy as np
import matplotlib.pyplot as plt
from analyzer.plotting import PlotObject, drawAs1DHist, drawAs2DHist
from hist import Hist

In [2]:
SIGNAL_NAMES = ['signal_312_1000_400',
                'signal_312_1000_600',
                'signal_312_1000_700',
                'signal_312_1000_800',
                'signal_312_1000_900',
                'signal_312_1200_400',
                'signal_312_1200_600',
                'signal_312_1200_700',
                'signal_312_1200_800',
                'signal_312_1200_900',
                'signal_312_1200_1000',
                'signal_312_1200_1100',
                'signal_312_1300_400',
                'signal_312_1300_600',
                'signal_312_1300_1200',
                'signal_312_1400_400',
                'signal_312_1400_600',
                'signal_312_1400_1300',
                'signal_312_1500_400',
                'signal_312_1500_600',
                'signal_312_1500_900',
                'signal_312_1500_1000',
                'signal_312_1500_1100',
                'signal_312_1500_1200',
                'signal_312_1500_1300',
                'signal_312_1500_1350',
                'signal_312_1500_1400',
                'signal_312_1500_1450',
                'signal_312_2000_400',
                'signal_312_2000_600',
                'signal_312_2000_900',
                'signal_312_2000_1200',
                'signal_312_2000_1300',
                'signal_312_2000_1400',
                'signal_312_2000_1500',
                'signal_312_2000_1600',
                'signal_312_2000_1700',
                'signal_312_2000_1900']

In [3]:
s = SampleManager()
s.loadSamplesFromDirectory("datasets/")

a = AnalysisResult.fromFile("output_signal.pkl")
a_background = AnalysisResult.fromFile("output_background.pkl")
# hists = a.getMergedHistograms(s)
bg_hists = a_background.getMergedHistograms(s)

In [4]:
background_style = s.getCollection("Skim_QCDInclusive2018").style
window_width = 300

m13_m_points = []
m24_m_points = []
m3_top_3_no_lead_b_points = []
m14_m_points = []

In [6]:
hists = a.results["signal_312_1000_400"].getScaledHistograms(s, None)
signal_hist = hists["m14_vs_m13"]
background_hist = bg_hists["m14_vs_m13"]

Hist(
  Regular(60, 0, 3000, name='$m_{4}$1', label='$m_{4}$'),
  Regular(60, 0, 3000, name='$m_{3}$2', label='$m_{3}$'),
  storage=Weight()) # Sum: WeightedSum(value=1.4034e+06, variance=8.06148e+06) (WeightedSum(value=1.43333e+06, variance=8.13103e+06) with flow)

In [5]:
xvar = 'm14_vs_m13'
for signal in SIGNAL_NAMES:
    hists = a.results[signal].getScaledHistograms(s, None)
    signal_name_parts = signal.split('_')
    true_mtop = int(signal_name_parts[-2])
    true_mchi = int(signal_name_parts[-1])

    # if mchi/mtop >~ 0.7, we're in the compressed signal region
    s_over_root_b, bin_centers, points = pq.s_over_root_b_2D(hists, bg_hists, xvar, true_mchi)





[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,  34.14683557,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ..., 520.33477526,
         21.53935979,   0.        ],
       [  0.        ,   0.        ,   0.        , ..., 595.3728714 ,
        483.82995222,  26.93821498]]), array([   0.,   50.,  100.,  150.,  200.,  250.,  300.,  350.,  400.,
        450.,  500.,  550.,  600.,  650.,  700.,  750.,  800.,  850.,
        900.,  950., 1000., 1050., 1100., 1150., 1200

ValueError: too many values to unpack (expected 2)