In [1]:
import torch

In [69]:
x1 = torch.randint(0,3, (3,2))
x2 = torch.randint(0,3, (3,2))
m = torch.tensor([[1,0],[0,0]])

print(x1)
print(x2)
print(m)
trans = x1 @ m
print("Trans ", trans)
print("EIS " , torch.einsum('ai,ij->aj',x1,m,))
print(torch.einsum('...i,...i',x1,x2))
print(torch.einsum('...i,...i',trans,x2))
print("EIS 2 " , torch.einsum('ai,ij,aj->a',x1,m,x2))

tensor([[0, 0],
        [1, 2],
        [0, 0]])
tensor([[2, 1],
        [2, 2],
        [0, 2]])
tensor([[1, 0],
        [0, 0]])
Trans  tensor([[0, 0],
        [1, 0],
        [0, 0]])
EIS  tensor([[0, 0],
        [1, 0],
        [0, 0]])
tensor([0, 6, 0])
tensor([0, 2, 0])
EIS 2  tensor([0, 2, 0])


In [70]:
diff = torch.unsqueeze(x1, dim=1) - x2
print(diff)
print("EIS 2 " , torch.einsum('abi,ij,abj->ab',diff,m,diff))

tensor([[[-2, -1],
         [-2, -2],
         [ 0, -2]],

        [[-1,  1],
         [-1,  0],
         [ 1,  0]],

        [[-2, -1],
         [-2, -2],
         [ 0, -2]]])
EIS 2  tensor([[4, 4, 0],
        [1, 1, 1],
        [4, 4, 0]])
